name = "meadowsweet"
description = "Simple Ada MVC web framework"
version = "0.1.0-dev"

authors = ["RenÃ© Hartmann"]
maintainers = ["RenÃ© Hartmann <rhartmann@users.sourceforge.net>"]
maintainers-logins = ["rehartmann"]
licenses = "Apache-2.0"
website = "https://github.com/rehartmann/meadowsweet"
tags = ["mvc", "web"]

[[depends-on]]
servletada = "^1.8.1"
