name = "meadowsweet_json"
description = "JSON renderer for Meadowsweet, an MVC web framework"
version = "0.1.0-dev"

authors = ["René Hartmann"]
maintainers = ["René Hartmann <rhartmann@users.sourceforge.net>"]
maintainers-logins = ["rehartmann"]
licenses = "Apache-2.0"
website = ""
tags = ["json", "web", "mvc"]

[[depends-on]]
gnatcoll = "^25.0.0"

[[depends-on]]
meadowsweet = "*"

[[pins]]
meadowsweet = { path='..' }
