name = "phonebook"
description = "Meadowsweet sample application"
version = "0.1.0"

authors = ["René Hartmann"]
maintainers = ["René Hartmann <rhartmann@users.sourceforge.net>"]
maintainers-logins = ["rehartmann"]
licenses = "Apache-2.0"
website = ""
tags = ["mvc", "web"]

executables = ["phonebook"]

[[depends-on]]
servletada_aws = "^1.8.1"

[[depends-on]]
meadowsweet = "*"
meadowsweet_jintp = "*"

[[pins]]
meadowsweet = { path = "../.." }

[[depends-on]]
gnatcoll_sql = "^25.0.0"

[[depends-on]]
gnatcoll_postgres = "^25.0.0"
